### ISSUE TITLE
Kanban board - set up

### ISSUE THREAD

**Issue by Strangeal** [AdnanOlarmmi/Capstone-II#21]
# Group capstone: set up your Kanban board

## Learning objectives
- Use the Kanban board with filled-in tasks that have categories and time estimations to assign work in groups.

## Description

In this activity, my team prepared a Kanban board with a GitHub project. As this is the very first group project in our Microverse journey.
In order to copy the Kanban board quickly, we used a special script prepared for us.

### Project requirements

- Joined a Zoom call as team-mates. Only one person copied the board on behalf of the entire team but helped during the call.
- We created an empty repository for our group project.
- Followed the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects).
- Opened the GitHub project (Kanban board) in our team repo.
- Made sure that in the card titles we can see: `Student A`, `Student B`, or `Student C`.
- Made sure that each card starts with `[Xpt]` - that number indicates the number of `points` that shows how complex the task is. **1 point = 1 hour of work**.
- Our group includes two people - so, we removed all cards with `Student C` in the title._
- Decided who in the team is `Student A`, or `Student B`.
- Each of the team members assigned themselves to the correct cards. We then decided who will be the assignee for the cards marked as group tasks. All cards on our Kanban board have assignees.

## Link and notes

- [Here is the link to our GitHub project](https://github.com/users/AdnanOlarmmi/projects/1).
- We are a group of two smart individuals Adnan Ishaq 🙃 @AdnanOlarmmi  and Justice Bajeri 😃  @Strangeal.

## Work and submission mode

- We implemented the above requirements only in **one repository** in your group.

## Appreciation
- Thanks for the review 🙃

**Comment by prolajumokeoni** [comment]
Hi @Team 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the right link to your GitHub project (kanban board)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AdnanOlarmmi** [comment]
@prolajumokeoni Hi ma'am 🙂, what are we supposed to submit? 
a link to the main repo?

**Comment by prolajumokeoni** [comment]
> Hello, a link to your GitHub project (kanban board) that you created, this is the template you are to copy from  [here](https://github.com/microverseinc/curriculum-javascript/projects/1), Please go through the requirements

**Comment by sja-thedude** [comment]
## Required Changes ♻️

Hi @AdnanOlarmmi & @Strangeal, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good job so far
✔️ All cards added correctly

## Required 
- [ ] Kindly make sure to add `In review` column in kanban. You can have a look below.

https://user-images.githubusercontent.com/70269507/196165195-c11471b9-30cb-4cbf-86eb-04c7b46491d2.mov


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Qoosim** [comment]
# *Status: Approved* :100: :heavy_check_mark: 

Hi @team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

_**Kindly check an optional comment I left under the review**_ :pray: 

## Highlights

-  Kanban board set up correctly. :heavy_check_mark: 
-  Tasks assigned correctly. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/4247740/178047782-245100c0-a9eb-48a9-bc07-436b57b53596.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [OPTIONAL] Kindly arrange your titles in order. `In review` card should come before `done` card.

**Comment by AdnanOlarmmi** [comment]
@Qoosim Thank you very much, sir ❤️

**Comment by Qoosim** [comment]
@AdnanOlarmmi, You're most welcome brother :+1:
